#   **** Nay Oo Kyaw *** #
#   ** nayookyaw.nok@gmail.com *** #

version: '3.9'
services:
  nayhaproxy:
    container_name: nay_haproxy
    image : nayhaproxy
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - 2222:2222
      - 2223:2223